version: '3'

services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - ${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - mongo_network
    restart: unless-stopped

  adminmongo:
    image: mrvautin/adminmongo:latest
    container_name: adminmongo
    
    ports:
      - ${ADMINMONGO_PORT}
    environment:
      HOST: adminmongo
      CONN_NAME: "AdminConn"
      DB_USERNAME: ${MONGO_USER}
      DB_PASSWORD: ${MONGO_PASSWORD}
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: admin
    networks:
      - mongo_network
    restart: unless-stopped
    depends_on:
      - mongodb

# volumes:
#   mongodb_data:

networks:
  mongo_network: