version: '3'

services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - ${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo_network
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 2
      start_period: 10s

  adminmongo:
    image: mrvautin/adminmongo:latest
    container_name: adminmongo
    entrypoint: ["/bin/sh", "-c", "chmod -R u+x /app/user/node_modules; node app.js"]
    
    ports:
      - ${ADMINMONGO_PORT}
    environment:
      HOST: adminmongo
      CONN_NAME: "AdminConn"
      DB_USERNAME: ${MONGO_USER}
      DB_PASSWORD: ${MONGO_PASSWORD}
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: admin
    networks:
      - mongo_network
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:

networks:
  mongo_network: